server:
  port: 8086
  servlet:
    context-path: /smm
name:
  O(∩_∩)O哈哈~
teacher:
                          loves: 小爱同学yml(application.properties属性优先级比较高)
                          t-age: 66
stu1:
  name: 紫薇${random.int}号
  age: 20
  friendsList: 小明,小东
  friendsListPlus:
    - 小明yml
    - 小东yml
#    yml 支持复杂类型封装，yml中可以封装对象，使用$Value不行
#    yml 支持松散绑定 t-name 等同 tName
  mathTeacher: {t-name: 老皇帝, tAge: 1, loves: you}
  hobbies: {first: pinpgong,second: basketball,third: baseball}
  isWork: true
  birthday: 2020/01/01
  colleaguesSet:
    - 张三
    - 李四
    - 王五
person:
#  age: 300
#  email: 12580
  userName: 好孩子
  age: 3
  email: 12580@qq.com